# Generated by Django 5.1.1 on 2025-01-22 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GTA', '0002_contact_delete_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
    ]
