# Generated by Django 5.1.1 on 2025-01-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTA', '0003_remove_contact_email_remove_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=50, max_length=254),
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default=1000),
        ),
    ]
