# Generated by Django 5.1.1 on 2025-01-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTA', '0004_contact_email_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('enrollment_number', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
            ],
        ),
    ]
