# Generated by Django 5.1.1 on 2025-01-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTA', '0005_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='std_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=100)),
                ('studentAge', models.IntegerField(default=18)),
                ('genderMale', models.CharField(max_length=100)),
                ('genderFemale', models.CharField(max_length=100)),
                ('genderOther', models.CharField(max_length=100)),
                ('enrollmentNumber', models.TextField(default=200)),
                ('contact', models.IntegerField(default=15)),
                ('course', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
