# Generated by Django 5.1.1 on 2025-01-27 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GTA', '0007_alter_std_form_enrollmentnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='std_form',
            old_name='genderFemale',
            new_name='gender',
        ),
        migrations.RemoveField(
            model_name='std_form',
            name='genderMale',
        ),
        migrations.RemoveField(
            model_name='std_form',
            name='genderOther',
        ),
    ]
