# Generated by Django 5.1.1 on 2025-01-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTA', '0008_rename_genderfemale_std_form_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='crud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('photo', models.ImageField(upload_to='crud')),
            ],
        ),
    ]
