# Generated by Django 5.1.1 on 2025-01-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTA', '0009_crud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud',
            name='age',
            field=models.IntegerField(default=20),
        ),
    ]
