# Generated by Django 5.1.1 on 2025-02-14 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GTA', '0011_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
